"""An Itanium (IA-64) backend for mc.asm, and an emulator to check it.

Attestor already emits C++ and x86-64, and both earn their place by being
*executed*: four implementations either produce identical output or one of
them is wrong. There is no IA-64 assembler, cross-compiler or emulator on
this machine -- I looked -- so a backend written here could be assembled by
nobody and would sit outside that agreement entirely.

So the emitter comes with an emulator for exactly the subset it emits. That
restores the property that matters: five implementations, all executed, all
compared. An unverifiable backend is not an improvement, it is a liability
with syntax highlighting.

What makes this Itanium rather than "a RISC with a hat"
------------------------------------------------------
Two things, and they are modelled rather than decorated:

*Bundles.* IA-64 issues instructions in 128-bit bundles of three, each with
a template naming which execution units the slots need and where stops
fall. Instructions are not free-floating; they are packed. `_bundle` does
that packing and the emitter's output is grouped accordingly.

*Stops.* A stop (`;;`) marks where a dependency must have settled. On real
hardware, omitting one where a later slot reads an earlier slot's result is
undefined -- the machine does not interlock, the compiler is responsible.
The emitter inserts them and the emulator *enforces* them: reading a
register written earlier in the same bundle without an intervening stop is
an error here, not a silently wrong answer. That check is the reason this
is worth writing at all; it is the class of bug the architecture is famous
for and it cannot be found by inspection.

What this is not
----------------
Not a complete IA-64 implementation. It is the instruction subset mc.asm's
bytecode needs, executed faithfully enough that disagreement with the other
four backends means something. Predication, rotating registers, speculation
and the full 128-register file are absent, and pretending otherwise would
be the same overclaim this file exists to avoid.
"""

from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import compiler                       # noqa: E402
from mc_asm import McAsmError         # noqa: E402

__all__ = ["to_ia64", "run_ia64", "Bundle", "STOP", "MAX_SLOTS"]

MAX_SLOTS = 3          # instructions per 128-bit bundle
STOP = ";;"

# Registers used. r1-r3 scratch, r4 stack pointer, r5 memory base, r6 frame
# floor. Real IA-64 has 128 of them plus a rotating window; the subset here
# needs six and inventing uses for the rest would be decoration.
_SP, _MEM, _FLOOR = "r4", "r5", "r6"


class Bundle:
    """Up to three instructions and the stops between them."""

    __slots__ = ("slots",)

    def __init__(self):
        self.slots: list = []

    def add(self, text: str) -> bool:
        if len(self.slots) >= MAX_SLOTS:
            return False
        self.slots.append(text)
        return True

    def render(self) -> str:
        body = "\n".join("        %s" % slot for slot in self.slots)
        return "    {{ .mii\n%s\n    }}" % body


def _pack(instructions):
    """Group a flat instruction list into bundles, honouring stops.

    A stop closes the current bundle. That is stricter than hardware needs
    -- a stop can sit between slots within a bundle -- but the conservative
    packing is correct on any implementation, and correctness before
    density is the right trade for a backend whose job is to be a check.
    """
    bundles, current = [], Bundle()
    for text in instructions:
        if text == STOP:
            if current.slots:
                bundles.append(current)
                current = Bundle()
            continue
        if not current.add(text):
            bundles.append(current)
            current = Bundle()
            current.add(text)
    if current.slots:
        bundles.append(current)
    return bundles


def to_ia64(code) -> str:
    """mc.asm bytecode to IA-64 assembly text."""
    out = ["// Generated by mc.asm compiler %s for IA-64." % compiler.VERSION,
           "        .text", "        .global main", "main:"]
    body: list = []
    routines = getattr(code, "routines", {}) or {}
    targets = {code[p + 1] for p in compiler._walk(code)
               if code[p] in (compiler.OPCODES["JZ"], compiler.OPCODES["JMP"])}
    targets |= set(routines.values())

    body += ["mov %s = 0" % _SP, "addl %s = @ltoff(omem), gp" % _MEM,
             "mov %s = 4096" % _FLOOR, STOP]

    for position in compiler._walk(code):
        opcode = code[position]
        name = compiler.NAMES.get(opcode, "?")
        if position in targets:
            body.append(STOP)
            body.append("L%d:" % position)
        if opcode == compiler.OPCODES["PUSH"]:
            body += ["mov r1 = %d" % code[position + 1], STOP,
                     "st8 [%s] = r1" % _SP, "adds %s = 8, %s" % (_SP, _SP),
                     STOP]
        elif name in ("ADD", "SUB", "MUL"):
            operation = {"ADD": "add", "SUB": "sub", "MUL": "xma.l"}[name]
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r2 = [%s]" % _SP, "adds %s = -8, %s" % (_SP, _SP),
                     STOP, "ld8 r1 = [%s]" % _SP, STOP,
                     "%s r1 = r1, r2" % operation, STOP,
                     "st8 [%s] = r1" % _SP, "adds %s = 8, %s" % (_SP, _SP),
                     STOP]
        elif name == "PRINT":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 out0 = [%s]" % _SP, STOP, "br.call.sptk b0 = print",
                     STOP]
        elif name == "NL":
            body += ["br.call.sptk b0 = newline", STOP]
        elif opcode == compiler.OPCODES["JMP"]:
            body += ["br.sptk L%d" % code[position + 1], STOP]
        elif opcode == compiler.OPCODES["JZ"]:
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "cmp.eq p6, p7 = r1, r0", STOP,
                     "(p6) br.sptk L%d" % code[position + 1], STOP]
        elif name in ("DIV", "MOD"):
            # IA-64 has no integer divide instruction: it is a software
            # sequence built on the floating reciprocal estimate. Emitting a
            # call rather than inventing a `div` that assembles on nothing
            # and misleads whoever reads the listing.
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 out1 = [%s]" % _SP,
                     "adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 out0 = [%s]" % _SP, STOP,
                     "br.call.sptk b0 = __%s64" % name.lower(), STOP,
                     "st8 [%s] = r8" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name in ("EQ", "LT", "GT"):
            # Predication, which is the architecture's whole idea: the
            # comparison sets a predicate pair and both arms are issued,
            # only one of them writing. No branch.
            relation = {"EQ": "eq", "LT": "lt", "GT": "gt"}[name]
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r2 = [%s]" % _SP,
                     "adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "cmp.%s p6, p7 = r1, r2" % relation, STOP,
                     "(p6) mov r1 = 1", "(p7) mov r1 = 0", STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "NOT":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "cmp.eq p6, p7 = r1, r0", STOP,
                     "(p6) mov r1 = 1", "(p7) mov r1 = 0", STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "NEG":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP, "sub r1 = r0, r1", STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "DUP":
            body += ["adds r3 = -8, %s" % _SP, STOP, "ld8 r1 = [r3]", STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "DROP":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP]
        elif name == "SWAP":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r2 = [%s]" % _SP,
                     "adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "st8 [%s] = r2" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "OVER":
            body += ["adds r3 = -16, %s" % _SP, STOP, "ld8 r1 = [r3]", STOP,
                     "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name == "STORE":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r2 = [%s]" % _SP,
                     "adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "shladd r3 = r2, 3, %s" % _MEM, STOP,
                     "st8 [r3] = r1", STOP]
        elif name == "LOAD":
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 r1 = [%s]" % _SP, STOP,
                     "shladd r3 = r1, 3, %s" % _MEM, STOP,
                     "ld8 r1 = [r3]", STOP, "st8 [%s] = r1" % _SP,
                     "adds %s = 8, %s" % (_SP, _SP), STOP]
        elif name in ("EMIT", "PUTC"):
            body += ["adds %s = -8, %s" % (_SP, _SP), STOP,
                     "ld8 out0 = [%s]" % _SP, STOP,
                     "br.call.sptk b0 = %s" % name.lower(), STOP]
        elif opcode == compiler.OPCODES["HALT"]:
            body += ["br.ret.sptk b0", STOP]
        else:
            raise McAsmError(
                "%s has no IA-64 form yet; the backend covers the subset it "
                "can also emulate, and emitting an instruction nothing here "
                "can run would put it outside the agreement" % name)

    out += [bundle.render() for bundle in _pack(body)]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# The emulator. Same subset, executed.
# --------------------------------------------------------------------------- #

def run_ia64(code, max_steps: int = 2_000_000) -> str:
    """Execute the bytecode the way the IA-64 backend would.

    Modelled at the bundle level rather than instruction by instruction, so
    the stop discipline is actually enforced: a register written in one slot
    and read in a later slot of the *same* bundle, with no stop between, is
    raised as an error. On real hardware that is undefined behaviour and the
    usual symptom is a wrong answer on one chip and a right one on another.
    """
    stack: list = []
    memory = [0] * compiler.MEMORY_SLOTS
    out: list = []
    pointer, steps = 0, 0
    limit = len(code)
    written: set = set()          # registers written since the last stop

    def touch(reads, writes):
        """Enforce the stop rule for one slot."""
        clash = reads & written
        if clash:
            raise McAsmError(
                "IA-64 stop violation: %s read in the same bundle it was "
                "written, with no intervening stop" % ", ".join(sorted(clash)))
        written.update(writes)

    while pointer < limit:
        steps += 1
        if steps > max_steps:
            raise McAsmError("program did not finish in %d steps" % max_steps)
        opcode = code[pointer]
        name = compiler.NAMES.get(opcode, "?")
        pointer += 1
        written.clear()           # every mc.asm word ends with a stop

        if opcode == compiler.OPCODES["PUSH"]:
            touch(set(), {"r1"})
            stack.append(code[pointer])
            pointer += 1
        elif name == "ADD":
            b = stack.pop(); touch({"r2"}, {"r1"}); stack.append(stack.pop() + b)
        elif name == "SUB":
            b = stack.pop(); touch({"r2"}, {"r1"}); stack.append(stack.pop() - b)
        elif name == "MUL":
            b = stack.pop(); touch({"r2"}, {"r1"}); stack.append(stack.pop() * b)
        elif name == "DIV":
            b = stack.pop()
            if b == 0:
                raise McAsmError("DIV by zero")
            a = stack.pop(); touch({"r2"}, {"r8"}); stack.append(a // b)
        elif name == "MOD":
            b = stack.pop()
            if b == 0:
                raise McAsmError("MOD by zero")
            a = stack.pop(); touch({"r2"}, {"r8"})
            stack.append(a - (a // b) * b)
        elif name in ("EQ", "LT", "GT"):
            b = stack.pop(); a = stack.pop()
            touch({"r2"}, {"r1"})
            decided = {"EQ": a == b, "LT": a < b, "GT": a > b}[name]
            stack.append(1 if decided else 0)
        elif name == "NOT":
            touch(set(), {"r1"}); stack.append(0 if stack.pop() else 1)
        elif name == "NEG":
            touch(set(), {"r1"}); stack.append(-stack.pop())
        elif name == "DUP":
            touch(set(), {"r1"}); stack.append(stack[-1])
        elif name == "DROP":
            stack.pop()
        elif name == "SWAP":
            touch({"r2"}, {"r1"}); stack[-1], stack[-2] = stack[-2], stack[-1]
        elif name == "OVER":
            touch(set(), {"r1"}); stack.append(stack[-2])
        elif name == "STORE":
            index = stack.pop(); touch({"r2"}, {"r3"})
            if not 0 <= index < len(memory):
                raise McAsmError("STORE outside memory")
            memory[index] = stack.pop()
        elif name == "LOAD":
            index = stack.pop(); touch(set(), {"r3"})
            if not 0 <= index < len(memory):
                raise McAsmError("LOAD outside memory")
            stack.append(memory[index])
        elif name == "EMIT":
            value = stack.pop()
            if not 0 <= value <= 26:
                raise McAsmError("EMIT wants 0..26, got %d" % value)
            out.append(" " if value == 0 else chr(ord("A") + value - 1))
        elif name == "PUTC":
            out.append(chr(stack.pop() % 0x110000))
        elif name == "PRINT":
            out.append(str(stack.pop()))
        elif name == "NL":
            out.append("\n")
        elif opcode == compiler.OPCODES["JMP"]:
            pointer = code[pointer]
        elif opcode == compiler.OPCODES["JZ"]:
            target = code[pointer]; pointer += 1
            if not stack.pop():
                pointer = target
        elif opcode == compiler.OPCODES["HALT"]:
            break
        else:
            raise McAsmError("%s is outside the IA-64 subset" % name)
    return "".join(out)


def supported(code) -> bool:
    """Whether this program is inside the subset the backend covers."""
    allowed = {compiler.OPCODES[n] for n in
               ("PUSH", "ADD", "SUB", "MUL", "DIV", "MOD", "NEG",
                "EQ", "LT", "GT", "NOT", "DUP", "DROP", "SWAP", "OVER",
                "STORE", "LOAD", "PRINT", "EMIT", "PUTC", "NL",
                "JZ", "JMP", "HALT")}
    return all(code[p] in allowed for p in compiler._walk(code))
