#!/usr/bin/env python3
"""Vendored / library / generated code detection.

The single biggest source of false positives in Attestor is firing rules on code
the user did not write: third-party dependencies, generated bindings, syscall
tables, minified bundles. This module classifies a path (and optionally its
content) as first-party, vendored, generated, or test code, so downstream
scanners can suppress or deprioritize findings that are not the user's problem.

This is what turns a 20,000-finding self-scan into a signal you can act on."""
from __future__ import annotations

import os
import re
from dataclasses import dataclass

# Directory names that are almost always not first-party source.
VENDOR_DIR_MARKERS = {
    "node_modules", "site-packages", "dist-packages", "vendor", "vendored",
    "third_party", "third-party", "3rdparty", "external", "externals",
    "bower_components", "jspm_packages", "packages", ".venv", "venv", "env",
    "virtualenv", ".tox", "eggs", ".eggs", "wheels", "bundle", "bundled",
    "deps", "_deps", ".cargo", "go/pkg", "Pods", "Carthage", ".gradle",
    "target", ".m2", ".nuget", "obj", ".pub-cache",
}

# Directory names that indicate generated / build output.
GENERATED_DIR_MARKERS = {
    "build", "dist", "out", "output", "_build", "cmake-build-debug",
    "cmake-build-release", "generated", "gen", "__generated__", ".next",
    "coverage", "htmlcov", "site", "_site", "public", "migrations",
}

# Directory names that indicate test code (lower blast radius; deprioritize).
TEST_DIR_MARKERS = {
    "test", "tests", "testing", "__tests__", "spec", "specs", "fixtures",
    "testdata", "test_data", "examples", "example", "samples", "demo", "demos",
    "e2e", "integration", "benchmarks",
}

# Filename suffixes that indicate generated / minified / bundled artifacts.
GENERATED_FILE_SUFFIXES = (
    ".min.js", ".min.css", ".bundle.js", ".chunk.js", "-lock.json",
    ".lock", ".map", "_pb2.py", "_pb2_grpc.py", ".pb.go", ".g.dart",
    ".generated.ts", ".d.ts", ".freezed.dart", "_generated.py",
)

# Filename patterns (regex) for generated code.
GENERATED_FILENAME_RE = re.compile(
    r"(?:^|[._-])(?:generated|autogen|auto_gen|pb2|grpc)(?:[._-]|$)", re.I
)

# Content markers: if the first N bytes contain one of these, it is generated.
GENERATED_CONTENT_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "Code generated by",
    "This file was automatically generated",
    "Autogenerated by",
    "AUTO-GENERATED FILE",
    "@flow strict",  # common in vendored FB code
    "webpackBootstrap",
)

# Content signatures for specific noisy libraries (the pwntools problem).
# A file that is mostly a giant constant table of syscall numbers, opcodes, or
# CPU register names is reference data, not exploit code.
NOISY_LIBRARY_SIGNATURES = [
    (re.compile(r"pwnlib|pwntools", re.I), "pwntools"),
    (re.compile(r"\bSYS_[a-z_]+\s*=\s*\d+", ), "syscall_table"),
    (re.compile(r"__NR_[a-z0-9_]+\s*=\s*\d+"), "syscall_table"),
    (re.compile(r"\bcapstone\b|\bkeystone\b|\bunicorn\b", re.I), "disassembler"),
    (re.compile(r"shellcraft", re.I), "shellcode_lib"),
]

CONTENT_SNIFF_BYTES = 4096


@dataclass
class Classification:
    path: str
    category: str          # "first_party" | "vendored" | "generated" | "test"
    reason: str
    library: str = ""      # populated when a known noisy library is identified
    weight: float = 1.0    # multiplier applied to finding priority (0..1)


def _parts(path: str) -> list[str]:
    # Split on BOTH separators directly -- never round-trip through PurePath,
    # which re-inserts OS-native backslashes on Windows and breaks the split.
    return [p for p in re.split(r"[\\/]+", path) if p and p not in (".", "..")]


def _classify_by_path(path: str) -> Classification | None:
    parts_lower = [p.lower() for p in _parts(path)]
    base = parts_lower[-1] if parts_lower else ""

    for part in parts_lower:
        if part in VENDOR_DIR_MARKERS:
            return Classification(path, "vendored", f"under '{part}/'", weight=0.0)

    if base.endswith(GENERATED_FILE_SUFFIXES) or GENERATED_FILENAME_RE.search(base):
        return Classification(path, "generated", "generated filename", weight=0.0)

    for part in parts_lower:
        if part in GENERATED_DIR_MARKERS:
            return Classification(path, "generated", f"under '{part}/'", weight=0.1)

    for part in parts_lower:
        if part in TEST_DIR_MARKERS:
            return Classification(path, "test", f"under '{part}/'", weight=0.4)

    return None


def _classify_by_content(path: str) -> Classification | None:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            head = f.read(CONTENT_SNIFF_BYTES)
    except OSError:
        return None

    for marker in GENERATED_CONTENT_MARKERS:
        if marker in head:
            return Classification(path, "generated", f"content marker: {marker!r}", weight=0.0)

    for pat, lib in NOISY_LIBRARY_SIGNATURES:
        if pat.search(head):
            return Classification(
                path, "vendored", f"known noisy library: {lib}", library=lib, weight=0.05
            )

    # A file dominated by "NAME = <int>" constant assignments is a lookup table,
    # not application logic. This is what makes syscall tables scream "rootkit".
    lines = [ln for ln in head.splitlines() if ln.strip()]
    if len(lines) >= 20:
        const_like = sum(
            1 for ln in lines
            if re.match(r"\s*[A-Za-z_][A-Za-z0-9_]*\s*[:=]\s*(?:0x[0-9a-fA-F]+|\d+)\s*,?\s*$", ln)
        )
        if const_like / len(lines) > 0.7:
            return Classification(
                path, "generated", "constant/lookup table (>70% const assignments)", weight=0.1
            )

    return None


def classify(path: str, sniff_content: bool = True) -> Classification:
    """Classify a single file. First-party unless proven otherwise."""
    by_path = _classify_by_path(path)
    if by_path is not None:
        return by_path
    if sniff_content:
        by_content = _classify_by_content(path)
        if by_content is not None:
            return by_content
    return Classification(path, "first_party", "no vendor/generated markers", weight=1.0)


def is_first_party(path: str, sniff_content: bool = True) -> bool:
    return classify(path, sniff_content).category == "first_party"


def weight_for(path: str, sniff_content: bool = True) -> float:
    return classify(path, sniff_content).weight


def filter_findings(
    findings: list,
    path_getter=lambda f: getattr(f, "path", None) or (f.get("path") if isinstance(f, dict) else None),
    min_weight: float = 0.5,
    sniff_content: bool = True,
) -> tuple[list, list]:
    """Split findings into (kept, suppressed) by first-party weight.

    Returns findings whose file weight >= min_weight as kept, the rest as
    suppressed. A cache avoids re-classifying the same file repeatedly."""
    cache: dict[str, float] = {}
    kept, suppressed = [], []
    for finding in findings:
        p = path_getter(finding)
        if not p:
            kept.append(finding)
            continue
        if p not in cache:
            cache[p] = weight_for(p, sniff_content)
        (kept if cache[p] >= min_weight else suppressed).append(finding)
    return kept, suppressed


def summarize(root: str) -> dict:
    """Walk a tree and report the first-party vs vendored/generated breakdown."""
    counts = {"first_party": 0, "vendored": 0, "generated": 0, "test": 0}
    from_ext = (".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".java",
                ".go", ".rb", ".php", ".c", ".cpp", ".h", ".hpp", ".rs")
    for dirpath, dirnames, filenames in os.walk(root):
        for fname in filenames:
            if fname.endswith(from_ext):
                cls = classify(os.path.join(dirpath, fname))
                counts[cls.category] = counts.get(cls.category, 0) + 1
    total = sum(counts.values()) or 1
    return {
        "counts": counts,
        "total": total,
        "first_party_pct": round(counts["first_party"] / total * 100, 1),
    }
